### ISSUE TITLE
General coop and float issues on Mac and Windows

### ISSUE THREAD

**Issue by robin073** [wrathematics/coop#10]
Your team appears to have only developed and tested these packages in the Linux environment. Also not even sure who or what "wrathematics" is.

I'm developing proper numerical methods for gene expression, reanalyzing Affymetrix studies on NCBI GEO. (Most of the published literature and publicly archived analyses are often quite wrong. This project of mine was instigated by a request  from one of the senior biologists on several of the major genome sequencing projects.)

Your coop and float packages would be just the ticket for reducing the computational burdens of handling genome wide RNA expression data sets, which don't need full double precision arithmetic. Moreover, they easily could be handled on desktop 16GB Windows 10 and Mac OSX High Sierra machines with the proper arithmetic and compression software as is being developd in other application areas such as video signal processing. (See the latest season 4 of the HBO "Silicon Valley" DVD.)

But I've run into numerous issues of getting your software running at full performance or even installed on my machines. All sorts of problems with supported compliers and their options. I also don't think the GitHub interfaces are working correctly either for Windows or Macs.

BTW, I tried using Linux several years ago, but eventually gave up. Long story..

**Comment by wrathematics** [comment]
wrathematics is me. I'm just one guy.

It's true that I develop on Linux, but the package should work on Windows and Mac. It's currently building and passing CRAN checks for all platforms https://cran.r-project.org/web/checks/check_results_coop.html

If you can give some examples of what's going wrong when you try to build the package, I can try to help.
