### ISSUE TITLE
support for pairwise.complete.obs

### ISSUE THREAD

**Issue by rmflight** [wrathematics/coop#2]
Supporting the case when rows or columns of a matrix may have NA elements, but still want to calculate correlations between pairs, using only the entries that are non-NA between the pair.

Demonstration at the [gist](https://gist.github.com/rmflight/62879686cd2df22c27e0).

This is important because often times -omics data have lots of missing data, and `complete.obs` would trim to a very small number of features to use, so want to be able to consider completeness in a pairwise fashion.

**Comment by wrathematics** [comment]
Implemented in 1b72b107d90665895dadca0655a92c33321ef7dd for covariance and cosine.  Correlation coming soon.

**Comment by rmflight** [comment]
Very cool! Looking forward to making use of this.

**Comment by wrathematics** [comment]
Implemented in https://github.com/wrathematics/coop/commit/c7d5bd7f425a741a9a9db4a2355a91c017dec1f7.

It's only about 2.5x faster than R's version on my machine, but I have some ideas about improving the performance. But it is feature complete at this time.
