### ISSUE TITLE
Any reason why Linux version on Cran is not distributed?

### ISSUE THREAD

**Issue by pommedeterresautee** [wrathematics/coop#3]
On https://cran.r-project.org/web/packages/coop/index.html there are only Windows and Mac version.

I have compiled the project on Ubuntu but using dcgMatrix makes coop::cosine function yelling not enough space (matrix is huge, 250K, but sparse). Is it related to the fact that Linux is not supported on Cran?

![image](https://cloud.githubusercontent.com/assets/1029874/14206698/3f43df94-f815-11e5-884e-48663444acf7.png)

**Comment by wrathematics** [comment]
I think they pulled it because of an error with solaris.  I plan to submit the latest version soon which should hopefully solve the problem.
